apiVersion: v1
kind: Namespace
metadata:
  name: qr-botanist
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: qr-botanist
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi